"""initial schema

Revision ID: b4d99314cd34
Revises: 
Create Date: 2026-04-06 23:46:16.671592
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = 'b4d99314cd34'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'started_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('chats', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('consultations', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('consultations', 'is_paid',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('consultations', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('consultations', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('conversation_steps', 'completed_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('messages', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('telegram_chats', 'telegram_chat_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('telegram_chats', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('telegram_users', 'telegram_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('telegram_users', 'is_bot',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('telegram_users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('telegram_users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('telegram_users', 'is_bot',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('telegram_users', 'telegram_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('telegram_chats', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('telegram_chats', 'telegram_chat_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('messages', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('conversation_steps', 'completed_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('consultations', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('consultations', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('consultations', 'is_paid',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('consultations', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('chats', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('chats', 'started_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
